receivers:
  castai-audit-logs:
    castai_api_url:           ${env:CASTAI_API_URL} # Use CASTAI_API_URL env variable to override default API URL (https://api.cast.ai/)
    castai_api_token:         ${env:CASTAI_API_TOKEN} # Use CASTAI_API_TOKEN env variable to provide token
    castai_poll_interval_sec: 10 # This parameter defines poll cycle in seconds.
    castai_page_limit:        10 # This parameter defines the max number of records returned from the backend in one page.
    castai_storage:
      type: "in-memory"
      back_from_now_sec: 3600

exporters:
  file:
    path:           ./audit_logs.log
    flush_interval: 100ms

processors:

extensions:
  health_check:

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    logs:
      receivers: [castai-audit-logs]
      processors: []
      exporters: [file]
