receivers:
  castai-audit-logs:
    castai_api_url:           ${env:CASTAI_API_URL} # Use CASTAI_API_URL env variable to override default API URL (https://api.cast.ai/)
    castai_api_token:         ${env:CASTAI_API_TOKEN} # Use CASTAI_API_TOKEN env variable to provide token
    castai_poll_interval_sec: 10 # This parameter defines poll cycle in seconds.

exporters:
  file:
    path:           ./audit_logs.log
    flush_interval: 100ms

processors:

service:
  pipelines:
    logs:
      receivers: [castai-audit-logs]
      processors: []
      exporters: [file]
