{{- if .Values.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-otel-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-otel-collector.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-otel-collector.annotations" . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.apiKey }}
  API_KEY: {{ required "apiKey must be provided" .Values.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}